name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rangadm/salary_calculator:${{ github.sha }}

  update-manifest-stage:
    runs-on: ubuntu-latest
    needs: ["build-and-push"]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: RangaDM/Salary-Calculator-gitops-infra
          ref: "main"
          token: ${{ secrets.G_TOKEN }}
      - name: setup git config
        run: |
          git config --global user.email "rangamaithreepala@gmail.com"
          git config --global user.name "RangaDM"
      - name: update deployment manifest
        run: |
          COMMIT_SHA=${{ github.sha }}
          IMAGE_NAME="rangadm/salary_calculator:${COMMIT_SHA}"
          sed -i "s#\(image: \).*#\1${IMAGE_NAME}#g" deployment.yaml
          git add deployment.yaml
          git commit -m "Update image to ${IMAGE_NAME}"
      - name: push changes
        run: |
          git push origin main

